apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: stack-service
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/rate-limit: "100"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - api.stack-platform.com
    secretName: stack-service-tls
  rules:
  - host: api.stack-platform.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: stack-service
            port:
              number: 80
