apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: stack-service
  labels:
    app: stack-service
spec:
  selector:
    matchLabels:
      app: stack-service
  endpoints:
  - port: metrics
    path: /metrics
    interval: 30s
    scrapeTimeout: 10s
